- job:
    name: rust-osauth-exercises
    parent: rust-base
    description: |
      Run rust-auth acceptance test on master branch
    run: playbooks/rust-osauth-exercises.yaml
    nodeset: ubuntu-focal

- job:
    name: rust-osauth-exercises-xena
    parent: rust-osauth-exercises
    description: |
      Run rust-auth acceptance test on xena branch
    vars:
      global_env:
        OS_BRANCH: stable/xena

- job:
    name: rust-osauth-exercises-wallaby
    parent: rust-osauth-exercises
    description: |
      Run rust-auth acceptance test on wallaby branch
    nodeset: ubuntu-bionic
    vars:
      global_env:
        OS_BRANCH: stable/wallaby

- job:
    name: rust-osauth-exercises-victoria
    parent: rust-osauth-exercises
    description: |
      Run rust-auth acceptance test on victoria branch
    nodeset: ubuntu-bionic
    vars:
      global_env:
        OS_BRANCH: stable/victoria

- job:
    name: rust-osauth-exercises-ussuri
    parent: rust-osauth-exercises
    description: |
      Run rust-auth acceptance test on ussuri branch
    nodeset: ubuntu-bionic
    vars:
      global_env:
        OS_BRANCH: stable/ussuri
    voting: false

- job:
    name: rust-osauth-exercises-train
    parent: rust-osauth-exercises
    description: |
      Run rust-auth acceptance test on train branch
    nodeset: ubuntu-bionic
    vars:
      global_env:
        OS_BRANCH: stable/train
    voting: false

- job:
    name: rust-osauth-exercises-nightly
    parent: rust-base
    description: |
      Run rust-auth acceptance test on master branch with nightly rust.
    run: playbooks/rust-osauth-exercises.yaml
    vars:
      rustup_toolchain: nightly
    voting: false

- project:
    name: dtantsur/rust-osauth
    check:
      jobs:
        - rust-osauth-exercises
        - rust-osauth-exercises-xena
        - rust-osauth-exercises-wallaby
        - rust-osauth-exercises-victoria
        - rust-osauth-exercises-ussuri
        - rust-osauth-exercises-train
        - rust-osauth-exercises-nightly
